### PR TITLE
AGM

### PR DESCRIPTION
**Pull request by NAThompson**

### CODE REVIEW

**Comment by ckormanyos** [comment]
This is cool.
Should we give it a try in some of the GSoC 2020 work, where we are using AGM for pi and log?
Or in a while? Or soon?

**Comment by NAThompson** [comment]
The file `reporting/accuracy/test_agm.cpp` demonstrates ~2ULP accuracy over the interval [1,10000]. So I think it can be used whenever you like!

**Comment by NAThompson** [comment]
Ooh the [mpmath](http://mpmath.org/doc/current/functions/powers.html) agm docs are quite good.

**Comment by NAThompson** [comment]
Looks like `mpfr` has an AGM as well: [mpfr_agm](https://tspiteri.gitlab.io/gmp-mpfr-sys/mpfr/MPFR-Interface.html).

Should this be wrapped in multiprecision?

**Comment by NAThompson** [comment]
I realize now that the 'vanilla AGM' is not all that useful; the variations on the theme are really powerful. In any case, this is still should still be a good starting point for other ideas.

**Pull request merged**
