### PR TITLE
Remove C-Style Casts

### PR DESCRIPTION
**Pull request by mborland**
More related to #740 @NAThompson

### CODE REVIEW

**Comment by NAThompson** [comment]
@mborland : Do you have permissions to merge? The diffs look good to me. . .

**Comment by mborland** [comment]
> @mborland : Do you have permissions to merge? The diffs look good to me. . .

I do not. I'll ping you when it's good.

**Comment by jzmaddock** [comment]
> I do not. I'll ping you when it's good.

Looks good to me too - Matt you should have write access now, please do go ahead and merge when ready.

**Comment by mborland** [comment]
Last test is hung so merging.

**Pull request merged**
