### PR TITLE
Fix for MSVC CI Failures

### PR DESCRIPTION
**Pull request by mborland**
Should reduce noise from the CI system while waiting for https://github.com/boostorg/random/pull/76 to be merged

### CODE REVIEW

**Comment by mborland** [comment]
@NAThompson This suppressed a good number of the Windows failures. Previously all MSVC versions and language standards were failing for the `../tools` tests

**Comment by mborland** [comment]
@NAThompson Do you have a solution for issue #465? If it is just increasing the tolerance I can throw that in here. Once that is fixed CI should finally be green.

**Comment by jzmaddock** [comment]
> Do you have a solution for issue #465? If it is just increasing the tolerance I can throw that in here. Once that is fixed CI should finally be green.

Has the code been fed through `std_real_concept` to check there are no mistakenly called double precision std library functions?

**Comment by NAThompson** [comment]
Yeah I need to actually think about that problem; will try to get to it soon!

**Comment by mborland** [comment]
I merged develop just to verify, but I believe this PR resolves all the outstanding CI failures except the two stemming from that issue.

**Comment by evanmiller** [comment]
@mborland Looking at the logs, the two `ooura_fourier_integral_test` failures appear to be unrelated. The Windows failure looks like another `bigobj` problem, so you should be able to fix it the same way the Daubechies tests were fixed.

However, it looks like the big object problems can be fixed with `-Wa,-mbig-obj` instead of skipping the compilation via ifdef. This is already done for a few tests, see e.g.

https://github.com/boostorg/math/blob/develop/test/Jamfile.v2#L490

Might be worth investigating if you haven't done so already.

**Comment by mborland** [comment]
@evanmiller Good call. The jamfile already had `/bigobj` for `daubechies_scaling_test` and `daubechies_wavelet_test` using MSVC; just needed to add it for mingw runs.

**Comment by mborland** [comment]
This should be good to go. Only two remaining errors are issue #465.

**Pull request merged**
