### PR TITLE
Fix for issue #810

### PR DESCRIPTION
**Pull request by mborland**
Addresses 0 as null pointer constant and sign compare warnings as well.

### CODE REVIEW

**Comment by jzmaddock** [comment]
The failure is unconnected but worrying (GCC-9 and gun++11 mode):

```
testing.capture-output ../../../bin.v2/libs/math/test/test_chatterjee_correlation.test/gcc-9/debug/link-static/threading-multi/visibility-hidden/test_chatterjee_correlation.run

====== BEGIN OUTPUT ======

Error at test_chatterjee_correlation.cpp:test_paper:130:

  Mollified relative error in float precision is 0.0561, which exceeds 0.012, error/tol  = 4.68.

  Expected: +0.828877568 = +0x1.a862a4p-1

  Computed: +0.884999990 = +0x1.c51eb8p-1

  ULP distance: +941578

malloc(): invalid next size (unsorted)

Aborted (core dumped)
```

**Comment by jzmaddock** [comment]
At https://drone.cpp.al/boostorg/math/768/197/2

**Comment by jzmaddock** [comment]
See also https://github.com/boostorg/math/pull/812 which extends this PR with further tests.
(no reason not to go ahead and merge this one though).

**Comment by mborland** [comment]
> The failure is unconnected but worrying (GCC-9 and gun++11 mode):
> 
> ```
> testing.capture-output ../../../bin.v2/libs/math/test/test_chatterjee_correlation.test/gcc-9/debug/link-static/threading-multi/visibility-hidden/test_chatterjee_correlation.run
> 
> ====== BEGIN OUTPUT ======
> 
> Error at test_chatterjee_correlation.cpp:test_paper:130:
> 
>   Mollified relative error in float precision is 0.0561, which exceeds 0.012, error/tol  = 4.68.
> 
>   Expected: +0.828877568 = +0x1.a862a4p-1
> 
>   Computed: +0.884999990 = +0x1.c51eb8p-1
> 
>   ULP distance: +941578
> 
> malloc(): invalid next size (unsorted)
> 
> Aborted (core dumped)
> ```

I think that test can be safely removed from CI testing. I'll look at it this week and open a PR for it.

**Pull request merged**
