### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bwignall**
Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos.

### CODE REVIEW

**Comment by NAThompson** [comment]
Wow! Just took a look through these diffs and didn't see any that would screw stuff up. So pending a build I'm happy; but maybe a few a British English?

**Comment by bwignall** [comment]
@NAThompson , that's entirely possible. I took any entry in the Wikipedia page as a possible typo, without consideration for cross-country variations, and I naively took its suggestion as the preferred spelling.

**Comment by NAThompson** [comment]
Ok, do you have script which does these changes? This looks nice to me, but it might also be helpful to apply it periodically in the future.

**Comment by pabristow** [comment]
I'm shocked - I've re-read all this several times and fixed dozens of typos :-(

I'd like to use the script on the Multiprecision docs too as I am working on a revision of this too.

(I will go though all the changed proposed and check them out.)

**Comment by bwignall** [comment]
@NAThompson , @pabristow : I will try to put up something by the end of the week. It's a simple (<100 LOC), naive, regex-based script, but it (semi-)automates this.

**Comment by NAThompson** [comment]
@jzmaddock : You good with merging or do you want to wait until you finish your other PRs to avoid merge conflicts?

**Comment by jzmaddock** [comment]
I've just corrected one strange doubled-up work, but other than that all looks good so I've gone ahead and merged.

This is really good useful stuff too - many thanks for this!!

**Comment by jzmaddock** [comment]
Ooops, doubled up *word*.  You see, typos even here!

**Comment by bwignall** [comment]
@NAThompson , @pabristow : https://github.com/bwignall/typochecker now contains the script.

**Comment by pabristow** [comment]
Many thanks for this.  I'll give it a whirl on Boost.Multiprecision - though of course since I have carefully proof-read it recently there won't be any typos will there?   ;-)

**Pull request merged**
