### PR TITLE
Add standalone testing to bezier polynomials

### PR DESCRIPTION
**Pull request by mborland**
A copy of #656 rebased against the develop branch.

### CODE REVIEW

**Comment by NAThompson** [comment]
Yup, you're right; it's gone. That's a bug in github!

**Comment by NAThompson** [comment]
I merged before testing completed because 1) we're a bit backed up, 2) we know develop is broken. We can open a new PR if necessary.

**Comment by jzmaddock** [comment]
> I merged before testing completed because 1) we're a bit backed up, 2) we know develop is broken. We can open a new PR if necessary.

What's broken?  There's stuff that still needs merging to master...

**Comment by mborland** [comment]
> > I merged before testing completed because 1) we're a bit backed up, 2) we know develop is broken. We can open a new PR if necessary.
> 
> What's broken? There's stuff that still needs merging to master...

The bezier polynomial test was broken on develop but fixed here. CI looks fine now.

**Comment by NAThompson** [comment]
The code wasn't so much broken as the process. Matt made a PR against my PR. I merged that PR with the intent on immediately merging Matt's PR on top of mine, for a clean build. But I deleted my branch after merge, which autoclosed Matt's PR. I "undeleted" the branch but Matt's PR was pwned. So Matt had to reopen a new PR, which was then on a broken develop.

**Pull request merged**
