### PR TITLE
C++11 initializer_list constructor and assignment for polynomial class

### PR DESCRIPTION
**Pull request by jeremy-murphy**
A constructor and copy assignment operator from `initializer_list`.
Semantics are copied from `vector` in libstdc++.

### CODE REVIEW

**Comment by jeremy-murphy** [comment]
I made a brief example of initializer_list construction, so I think this one is ready to go.

**Comment by jzmaddock** [comment]
Thanks for this!

Can we please change the #if logic to use the appropriate Boost.Config macros?

**Comment by jzmaddock** [comment]
Never mind, I merged it locally and made the changes.
Also changed the call to pow with integer arguments to use a trivial integer-power routine - fixes a build failure on VC10, but also loss of digits when T is a built in type with more digits than double (ie long long).

It's a pretty brain dead power function and there's no error handling - any exponent in double figures will likely cause numeric overflow :(  Note sure what we do about that...

**Comment by jeremy-murphy** [comment]
Ah, sorry, I wasn't aware of those particular Boost macros. Next time.

I'm fairly sure that there are integer power algorithms in Knuth and at least for 32-bit integers in Hacker's Delight, so I should be able to come up with something. Begs the question of where such an algorithm should go in Boost in general.

**Comment by jzmaddock** [comment]
> I'm fairly sure that there are integer power algorithms in Knuth and 
> at least for 32-bit integers in Hacker's Delight, so I should be able 
> to come up with something. Begs the question of where such an 
> algorithm should go in Boost in general.
>

Good question, I guess we haven't provided this before because:

* For floating point bases, use of std::pow is just as quick typically.
* For built-in integer types as bases, overflow occurs so easily, that 
it's questionable whether these are viable general purpose algorithms?

Either way, the version I posted could use having the tail recursion 
removed at the very least...

**Comment by jeremy-murphy** [comment]
Right, yeah, it's a curious problem in that std::pow is satisfactory for most cases, but the fact that it's wrong for some cases does create the need at least for a correct algorithm. I didn't see anything in Knuth specific to integral bases but I only looked quickly. HD has this function, which is more or less an iterative version:
```C
int iexp(int x, unsigned n)
{
    int p = x, y = 1;
    while (true)
    {
        if (n & 1) y *= p;
        n >>= 1;
        if (n == 0) return y;
        p *= p;
    }
}
```
We can of course play with the types.

**Pull request merged**
