### PR TITLE
Fix for issue #764

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by mborland** [comment]
Only failure if CI package installation so merging. Gets us back to green.

**Comment by jzmaddock** [comment]
Can we not fix the source?  It looks like something is including C++ headers in C mode?

**Comment by jzmaddock** [comment]
Unable to reproduce with msvc-14.3.0, once the huge download I have in progress completes I'll update to 14.3.1 and try again.

**Comment by jzmaddock** [comment]
Reproduced, dealt with upstream in Boost.Config.

**Pull request merged**
