### PR TITLE
Retry adding repos

### PR DESCRIPTION
**Pull request by mborland**
From https://github.com/boostorg/math/issues/549. There is currently [no official way](https://github.community/t/retry-for-failed-steps/17136) to retry steps so this adds extra steps that only run on failure.

### CODE REVIEW

**Comment by jzmaddock** [comment]
That's a neat solution - thanks for this Matt - hopefully we can cut down the churn a bit!

**Comment by mborland** [comment]
@jzmaddock This is green, but it does not look like any of the retry steps ran. At least we know that skipping those steps on success works.

**Comment by jzmaddock** [comment]
OK, lets merge and see!  Thanks for this.

**Comment by ckormanyos** [comment]
This is cool, ... I was having difficulty moulding and contorting my mindset to _didn't run is the new green_.

**Pull request merged**
