### PR TITLE
Fix for #767

### PR DESCRIPTION
**Pull request by mborland**
Adds include guards for the usage of fftw3 and gives a hard error if it is unavailable.

### CODE REVIEW

**Comment by mborland** [comment]
@NAThompson If this solves your problem it's good to merge. All the failures are on the CIs side.

**Comment by NAThompson** [comment]
@mborland : Thanks!

**Comment by NAThompson** [comment]
@mborland : Forgive my CMake stupidity, but how do you run the tests?

I'm trying:

```
build$ cmake ../ -G Ninja
build$ ninja
build$ ctest -V
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
```

**Comment by mborland** [comment]
It may be improper, but it works:

```
cd .../boost/libs/math
cmake .
make -j11
```

**Pull request merged**
