### PR TITLE
Remove boost.algorithm dependency

### PR DESCRIPTION
**Pull request by mborland**
@NAThompson

### CODE REVIEW

**Comment by NAThompson** [comment]
@mborland : thanks looks good!

**Comment by mborland** [comment]
@NAThompson I am not sure why this feature took till C++20 to make it in, but oh well. CI is clean.

**Comment by NAThompson** [comment]
@mborland : Do you think this should go into an anonymous namespace so we don't break anyone else who has hand-coded and `endswith`?

**Comment by jzmaddock** [comment]
@NAThompson A "detail" namespace would be better than an anonymous one: anonymous namespaces don't actually hide anything, just change the linkage.

**Comment by mborland** [comment]
@jzmaddock Exactly my thought

**Comment by mborland** [comment]
@NAThompson I added the detail namespace. Do you think it is worthwhile to bring this version of `ends_with` up into a higher level header in tools (something like adding a boost/math/tools/algorithms.hpp) or fine here since its the only use?

**Comment by NAThompson** [comment]
@mborland : Not right now. I believe this is the only thing that could use it. @jzmaddock can overrule at his leisure.

**Pull request merged**
