### PR TITLE
Interpolate a uniform grid with a bilinear function.

### PR DESCRIPTION
**Pull request by NAThompson**

### CODE REVIEW

**Comment by NAThompson** [comment]
@mborland , @jzmaddock : I got this error from the CircleCI 'inspect' tool:

```
|include|
  include/boost/math/interpolators/bilinear_uniform.hpp:
    C-style assert macro on line 49
    C-style assert macro on line 50
    Non-ASCII:         out << "(x₀, y₀) = (" << bu.x0_ << ", " << bu.y0_ << "), (Δx, Δy) = (" << bu.dx_ << ", " << bu.dy_ << "), "
```

Are non-ASCII characters in print functions actually a problem for us? I find them kinda nice . . .

**Comment by jzmaddock** [comment]
>Are non-ASCII characters in print functions actually a problem for us? I find them kinda nice . . .

That's one for the mailing list.... but if I remember correctly, folks building on windows with far-eastern character sets run into nasty issues with the source being unparsable if there's Unicode in there.

**Comment by NAThompson** [comment]
It looks like MSVC 14.2 really doesn't like the indexing integer being deduced from `decltype(fieldData.size())`, to wit:

```cpp
bilinear_uniform(RandomAccessContainer && fieldData, decltype(fieldData.size()) rows, decltype(fieldData.size()) cols, ...
```

gets us the following compiler error:

```
D:\a\math\boost-root\boost/math/interpolators/bilinear_uniform.hpp(30): error C2228: left of '.size' must have class/struct/union
D:\a\math\boost-root\boost/math/interpolators/bilinear_uniform.hpp(30): note: type is 'unknown-type'
```

Does anyone know how to avoid the sign compare warnings of (say) `size_t rows, size_t cols` while working around this restriction?

**Comment by NAThompson** [comment]
Build error was a timeout.

**Pull request merged**
