### PR TITLE
Fix derivative of pow(x,y) when x=0

### LINKED ISSUE #445: Autodiff pow(0,N) always returns undefined derivatives
Line 1415 of `autodiff.hpp` divides by zero when `pow(0, N)` is called. This leads to undefined derivatives for something like x^2.

Might be better to call `pow(x,N-1)`.

### PR DESCRIPTION
**Pull request by pulver**
Fixes #445

### CODE REVIEW

**Comment by pulver** [comment]
All of the Travis and Appveyor CI tests passed for this PR except for one Appveyor test:
image
https://ci.appveyor.com/project/jzmaddock/math/builds/36262373
apparently due to a 1-hour timeout. In contrast, a [recent sucessful build]( https://ci.appveyor.com/project/jzmaddock/math/builds/36294269) took just under 58 minutes for that same test.

Suggestions?

**Comment by NAThompson** [comment]
@pulver : That happens on occasion; it's nothing to worry about.

Is it ready to merge?

**Comment by pulver** [comment]
> Is it ready to merge?

Yes.

**Review by wgledbetter — COMMENTED** [review]
Looks good to me. Thanks for being responsive!

**Pull request merged**
