### PR TITLE
Remove boost.lexical cast and boost.core dependencies

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by mborland** [comment]
All the CI failures on this one are: "GitHub Actions has encountered an internal error when running your job." Should be good to go.

**Comment by jzmaddock** [comment]
@mborland : try compiling :

```
g++ -I. -c -DBOOST_MATH_STANDALONE libs/math/test/compile_test/*.cpp
```

and there are gazillions of errors.  The first is caused by a `static_assert(false` which is *always* triggered by gcc, not just when the containing function is instantiated, the condition has to depend on a dependent template type parameter, the next by use of BOOST_STRINGIZE.

**Comment by mborland** [comment]
> @mborland : try compiling :
> 
> ```
> g++ -I. -c -DBOOST_MATH_STANDALONE libs/math/test/compile_test/*.cpp
> ```
> 
> and there are gazillions of errors. The first is caused by a `static_assert(false` which is _always_ triggered by gcc, not just when the containing function is instantiated, the condition has to depend on a dependent template type parameter, the next by use of BOOST_STRINGIZE.

You are correct. I have a branch that contains this PR and #588 so that I could begin fully testing Standalone. It has several little fixes like the ones you described. Are you good with me closing both of those PRs and rolling them into one?

**Comment by mborland** [comment]
Consolidated into #597

**Comment by jzmaddock** [comment]
> Are you good with me closing both of those PRs and rolling them into one?

Nod.  Sounds good to me!

**Pull request closed without merging**
