### PR TITLE
Add mapairy/holtsmark/saspoint5 distributions.

### PR DESCRIPTION
**Pull request by jzmaddock**
See https://github.com/boostorg/math/pull/1154
See https://github.com/boostorg/math/pull/1155
See https://github.com/boostorg/math/pull/1156

### CODE REVIEW

**Comment by jzmaddock** [comment]
Drone failures are spurious "no space left on device" errors, we may have to look at that separately.  @mborland ?

Merging.

**Comment by mborland** [comment]
@sdarwin Can you see why we would be getting no space left on disk errors on the drone run? These new functions/tests should only have affected the runs for distribution_tests. Thanks.

**Comment by tk-yoshimura** [comment]
@jzmaddock 
Thank you for your help in implementing these distributions.
I am developing my own numerical modules for multi-precision floating point numbers, probability distributions, special functions, and numerical integrals.
I am very proud to have my implementation reviewed by you, a leading expert in these fields!

**Comment by mborland** [comment]
> Drone failures are spurious "no space left on device" errors, we may have to look at that separately. @mborland ?
> 
> Merging.

Should be fixed now. From Sam on slack:

99% of the time, the drone autoscale instances are deleted after use.     Less than 1% of the time, something gets hung up, and the instance stays around.    There were two such machines. After 4 days, they have accumulated a large number of docker images: [ghcr.io/anarthal-containers/build-clang18](http://ghcr.io/anarthal-containers/build-clang18) .   Those fill up the disk.     The instances have now been deleted.
Also, a somewhat large image cppalliance/droneubuntu2304   Since that is not a LTS, I will make a noted to delete that, next week.   Please remove 23.04 any CI files and switch to 24.04.

**Pull request merged**
