### PR TITLE
Fix cstdfloat numeric limits detection macro for libstdc++14

### PR DESCRIPTION
**Pull request by mborland**
Reported by @jwakely here: https://github.com/boostorg/math/pull/993

### CODE REVIEW

**Comment by mborland** [comment]
Failures are internal CI errors. Merging

**Comment by jwakely** [comment]
Thanks! We'll get this backported to the Fedora packages.

**Comment by jwakely** [comment]
Feel free to @ me here if you want me to check gcc-config-related changes like this, I'd rather review them _before_ they make it into a release than when we're packaging it for Fedora :-)

**Comment by mborland** [comment]
> Feel free to @ me here if you want me to check gcc-config-related changes like this, I'd rather review them _before_ they make it into a release than when we're packaging it for Fedora :-)

Will do. Thanks.

**Pull request merged**
