### PR TITLE
MSVC 14_0 stdndards and has-include corrections

### PR DESCRIPTION
**Pull request by ckormanyos**
The purpose of this PR is to handle trivial syntax improvements mentioned in #1016.

### CODE REVIEW

**Comment by ckormanyos** [comment]
The lexical parser isn't into it.

```
fatal error C1012: unmatched parenthesis: missing ')'
```

I need to go with the former preprocessor stuff, or at least try it out first.

**Comment by ckormanyos** [comment]
Well the code logic is OK and things are going green but i messed up the GHA logic a bit and a few too many runners are being run. So this will need one more logic fix on the YAML layer. Coming right up, ...

**Comment by jzmaddock** [comment]
>The lexical parser isn't into it.

It does work: Boost.Config is using it for all compilers including vintage msvc: https://github.com/boostorg/config/blob/d483059795f8bf77120ee423d1660532223e5795/include/boost/config/detail/select_stdlib_config.hpp#L18

**Comment by ckormanyos** [comment]
>> The lexical parser isn't into it.

> Boost.Config is using it for all ...

Ahhh good save, John. I tried the line:

```cpp
#if (defined(__has_include) && (__has_include(<stdfloat>)))
```

But the variation should be:

```cpp
#if (defined(__has_include)
#if (__has_include(<stdfloat>))
#include <stdfloat>
#endif
#endif
```

**Comment by ckormanyos** [comment]
> good save, John

John (@jzmaddock) could we agree on?

```cpp
#if defined(__has_include)
#if __has_include(<stdfloat>)
#include <stdfloat>
#endif
#endif
```

Cc: @mborland

**Comment by mborland** [comment]
> ```c++
> #if defined(__has_include)
> #if __has_include(<stdfloat>)
> #include <stdfloat>
> #endif
> #endif
> ```

That is the format that GCC recommends: https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html

**Comment by ckormanyos** [comment]
> the format that GCC recommends

Great thank you Matt (@mborland). I will cycle this through, then:

```cpp
#if defined __has_include
#  if __has_include (<stdfloat>)
#    include <stdfloat>
#  endif
#endif
```

**Comment by ckormanyos** [comment]
Matt (@mborland) while we are at it, I used super-rudimentary logic on the YAML-ing. Would you please take a look and see if you can agree to that? Or can we do better?

**Comment by mborland** [comment]
> Matt (@mborland) while we are at it, I used super-rudimentary logic on the YAML-ing. Would you please take a look and see if you can agree to that? Or can we do better?

It looks good to me. Definitely more compact than making it own config for one compiler.

**Comment by ckormanyos** [comment]
> t looks good to me.

Thanks Matt. OK let's let this thing cacle through. It is cycling green even with recent changes in develop to `denorm_min` in Multiprecision. These are in develop now.

I'm not sure if this is or is not expected. But I'm happy to observe that.

**Comment by ckormanyos** [comment]
Single failure on drone to clone. Merging.

**Pull request merged**
