### PR TITLE
Fix for issue 773

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by mborland** [comment]
@NAThompson do you concur with this handling of NaNs? I thought this would be much lighter weigh than throwing an exception.

**Comment by NAThompson** [comment]
@mborland : In computer graphics, nans always render black. So this is the correct behavior.

Why doesn't the std::isnan from std work?

**Comment by mborland** [comment]
> Why doesn't the std::isnan from std work?

Isn't the behavior or `boost::math::isnan` more stable across compilers/optimizations? Passing a NaN to `std::clamp` should be UB since `clamp` requires the less than comparable concept. I was trying to avoid this with configurations that replace `std::isnan` with `false`.

**Comment by NAThompson** [comment]
>  I was trying to avoid this with configurations that replace std::isnan with false.

Oh yeah that's just awful. . .

**Pull request merged**
