### PR TITLE
Conditionally Disable MP Testing 

### PR DESCRIPTION
**Pull request by mborland**
Should significantly reduce resource usage. Changes a macro used for testing under standalone so now you have to explicitly enable MP testing.

### CODE REVIEW

**Comment by jzmaddock** [comment]
Could we enable MP-testing for at least ONE compiler in CI?  Otherwise I fear breakages will go unnoticed.

**Comment by mborland** [comment]
> Could we enable MP-testing for at least ONE compiler in CI? Otherwise I fear breakages will go unnoticed.

Yes. Once the drone run finishes I will see what the delta in our resource usage is. If we need to whack testing down more I can continue to sprinkle that macro around, and then define it in a few CI runs.

**Comment by jzmaddock** [comment]
> Yes. Once the drone run finishes I will see what the delta in our resource usage is. If we need to whack testing down more I can continue to sprinkle that macro around, and then define it in a few CI runs.

Got it, cool.  I suspect the multiprc_concept_check_N tests are probably the worst offenders for memory usage.

**Comment by mborland** [comment]
@jzmaddock  I appreciate your comment in `test_1F1` that: `These next 2 tests take effectively "forever" to compile with clang:`

**Comment by mborland** [comment]
The two CI failures in drone are spurious.

**Pull request merged**
