### PR TITLE
Polynomial Stein gcd

### PR DESCRIPTION
**Pull request by jeremy-murphy**
This is the basic implementation required for using the "binary" gcd algorithm on a polynomial.

### CODE REVIEW

**Comment by jeremy-murphy** [comment]
Any thoughts here? I realize using `operator <` this way might be controversial.

**Comment by jzmaddock** [comment]
If we're going to have an operator <, then if the limb counts are the same, we should compare limb-by-limb I guess, with higher order limbs taking priority.

Is there precedent for polynomial ordering?

**Comment by jeremy-murphy** [comment]
Unfortunately, 99% of web results for polynomial ordering are about ordering the terms within a single expression and polynomial sorting is, well, about polynomial algorithms for sorting.  :)  I looked into this topic last year and my conclusion was that there was no precedent.

I believe `<` by itself is OK, it satisfies the concept of Strict Weak Ordering, my main concern is the interaction with `==`: elements that are equivalent according to the `<` relation are not necessarily equal according to `==`. Whereas they would be if `<` was a Total Ordering (I think -- I still get the strict/weak/partial/total terminology a bit mixed up). But is that terrible? My understanding is that the STL components only require a Strict Weak Ordering.

An argument in favour of this definition of `<` is that it is the most efficient for Stein gcd: a total ordering would also work but increases the complexity of ranking from constant to linear.

**Comment by jeremy-murphy** [comment]
Gah, I accidentally called the branch "Steiner" when I meant "Stein", how embarrassing.

**Comment by jzmaddock** [comment]
On 10/03/2016 01:58, Jeremy W. Murphy wrote:
>
> Gah, I accidentally called the branch "Steiner" when I meant "Stein", 
> how embarrassing.
>

I suspect he'll live with it ;)

**Comment by jzmaddock** [comment]
On 10/03/2016 01:55, Jeremy W. Murphy wrote:
>
> Unfortunately, 99% of web results for polynomial ordering are about 
> ordering the terms within a single expression and polynomial sorting 
> is, well, about polynomial algorithms for sorting. :) I looked into 
> this topic last year and my conclusion was that there was no precedent.
>
> I believe |<| by itself is OK, it satisfies the concept of Strict Weak 
> Ordering, my main concern is the interaction with |==|: elements that 
> are equivalent according to the |<| relation are not necessarily equal 
> according to |==|. Whereas they would be if |<| was a Total Ordering 
> (I think -- I still get the strict/weak/partial/total terminology a 
> bit mixed up). But is that terrible? My understanding is that the STL 
> components only require a Strict Weak Ordering.
>
> An argument in favour of this definition of |<| is that it is the most 
> efficient for Stein gcd: a total ordering would also work but 
> increases the complexity of ranking from constant to linear.
>

Understood, I'm just uncomfortable with this definition as is.

Can we either pass a functor to gcd for operator <, or else use a traits 
class for that operation within gcd, and then we could leave operator< 
undefined for polynomials?

**Comment by pabristow** [comment]
I trust you guys are saving this erudite discussion to record in the Boost.Math documentation ;-)

 

But I’ll do nothing until it has come to a conclusion…

 

Paul

**Comment by jeremy-murphy** [comment]
I think a traits class sounds like a good idea. It may well be too much to expect that a single `operator<` will optimally perform all the tasks expected of it for a polynomial. In the end, given that equality is defined by `a.data() == b.data()`, it is probably consistent for less than to be `a.data() < b.data()`.

What about right shift? I guess we could have a complementary left shift that increases the order of all the terms and adds a zero constant to the end. That would make the behaviour equivalent to integers, I think.

**Comment by jeremy-murphy** [comment]
I'll close this PR since I think the final result will look somewhat different.

**Pull request closed without merging**
