### PR TITLE
Vector barycentric

### PR DESCRIPTION
**Pull request by NAThompson**
Very simple, just makes the syntax for interpolating vector-valued functions a bit nicer.

### CODE REVIEW

**Comment by NAThompson** [comment]
Everyone cool with this getting merged?

**Comment by pabristow** [comment]
Slightly-informedly, yes.  Paul

**Comment by jzmaddock** [comment]
I've only given this the most cursory look, but I'm sure it's fine.  So I'd say go ahead and merge.

(Aside: my mother managed to break her hip last weekend, so I really have no time at all right now to look at anything much, but once she's moved to a nearer Hospital that should ease up hopefully!)

**Comment by NAThompson** [comment]
Very sorry to hear that.

I'll go ahead and post on codereview.stackexchange just to make sure I didn't do anything obviously stupid.

**Pull request merged**
