### PR TITLE
Add landau distribution

### PR DESCRIPTION
**Pull request by tk-yoshimura**
### Reference issue
https://github.com/boostorg/math/issues/1152

### What does this implement/fix?
Add Landau distribution.

### Additional information
This is an implementation of the following report I wrote:
[DOI](https://doi.org/10.36227/techrxiv.171822215.53612870/v2)

The scale parameter behavior of the Landau distribution is particular, and my implementation is Wolfram Alpha compliant.
https://reference.wolfram.com/language/ref/LandauDistribution.html

As of July 2024, the left tail values output by Wolfram Alpha have not converged to an asymptotic curve, which is different from my implementation.
N[PDF[LandauDistribution[0, pi/2], -15/2], 20]  
wolfram_negativeside_error

While every effort has been made to calculate the coefficients, this implementation should be fully verified.

### CODE REVIEW

**Comment by mborland** [comment]
This looks really good so far and I approved the CI run so hopefully we'll get some results shortly. Can you add a doc page for this as well? A good example is https://github.com/boostorg/math/blob/develop/doc/distributions/binomial.qbk.

**Comment by tk-yoshimura** [comment]
I have no experience with quickbook, so I need more time to create the document.

**Comment by mborland** [comment]
> I have no experience with quickbook, so I need more time to create the document.

No rush. It's a niche documentation system I believe used exclusively by boost.

**Comment by tk-yoshimura** [comment]
Please point out any deficiencies in the documentation.

I generated the image for the document.
Is this correct?

landau_define
landau_define

landau_loc
landau_scale

landau_pdf_cpp_fp64_pdf
landau_cdf_cpp_fp64_cdf
landau_cdf_cpp_fp64_ccdf

landau_pdf_cpp_fp128_pdf
landau_cdf_cpp_fp128_cdf
landau_cdf_cpp_fp128_ccdf

**Comment by jzmaddock** [comment]
Just looking at this now, many thanks for submitting this PR, detailed comments to follow shortly...

**Comment by tk-yoshimura** [comment]
@jzmaddock 
Thank you for the correction.
I am very honored to have been reviewed by you.

Is there anything I should correct about this PR in the future?

The behavior of the scale parameter is debatable.
landau_locbias

From the scipy that calls this boost, only the standard Landau distribution is used, and this is modified for scale and location parameters similar to other distributions.
This is not consistent with the WolframAlpha implementation or the parameters of the Levy Stable distribution.

I was very torn about which way to go on this issue to avoid confusion, but I designed it to conform to the WolframAlpha implementation.

**Comment by jzmaddock** [comment]
> Is there anything I should correct about this PR in the future?

I have one more fix to push (my mistake!), but also we need to complete the last bits of the docs, can you please push (to here is fine) the SVG version of the equation to `libs/math/doc/equations/`.  Also assuming the equation started out as LaTex, could you please add the LaTex source as a comment to the .qbk file?  It just speeds things up if any future maintenance is required.

Do you have .svg's of the graphs?  If so could you push them to `libs/math/doc/graphs/` ?  If not, then if you could add the .png's there, I'll fix up the docs to point to them.

>From the scipy that calls this boost, only the standard Landau distribution is used, and this is modified for scale and location parameters similar to other distributions.
This is not consistent with the WolframAlpha implementation or the parameters of the Levy Stable distribution.

>I was very torn about which way to go on this issue to avoid confusion, but I designed it to conform to the WolframAlpha implementation.

That sounds perfectly reasonable: do you happen to know which Landau used in his original paper and/or which is most useful for particle physics?  Whichever choice is made it needs to be carefully documented - can you add a sentence or two to the start of the docs (just after the scale and location are introduced) explaining the choice made?

Many thanks for the PR, and a nice job!  If you can push those extra bits, then I'll push those plus my one last change to the integration PR, and hopefully one last CI run should get this over the line!

**Comment by tk-yoshimura** [comment]
This is the SVG version of the graph.
I'm not sure if these are appropriate to commit due to their large file size, so I'm uploading them here.

## Define
define
```tex
\begin{equation*} 
    f(x; \mu, c)=\frac{1}{\pi c} \int_{0}^{\infty} \exp(-t) \cos \left( t \left( \frac{x-\mu}{c}\right) + \frac{2t}{\pi} \log \left( \frac{t}{c} \right)  \right) dt
\end{equation*}
```

## Location and Scale Parameter
landau_loc
landau_scale

## FP64 Accuracy
landau_pdf_cpp_fp64_pdf
landau_cdf_cpp_fp64_cdf
landau_cdf_cpp_fp64_ccdf

## FP128 Accuracy
landau_pdf_cpp_fp128_pdf
landau_cdf_cpp_fp128_cdf
landau_cdf_cpp_fp128_ccdf

**Comment by jzmaddock** [comment]
Thanks @tk-yoshimura : I'd forgotten how large those SVG ULP plots get!  I'll sort those out tomorrow.

**Comment by jzmaddock** [comment]
Thanks @tk-yoshimura : integration PR has been merged!

When the other distributions are all ready - maybe they are now?  Let me know and I'll work through the whole lot in one go.

**Comment by tk-yoshimura** [comment]
Thank you very much! @jzmaddock 
The other distributions have been corrected.

**Pull request closed without merging**
