### PR TITLE
Improve Heuman Lambda precision:

### PR DESCRIPTION
**Pull request by jzmaddock**
Make sure we pass 1 - k^2 down through the call stack otherwise we get cancellation errors.

### CODE REVIEW

**Comment by jzmaddock** [comment]
@mborland the clang/Mac errors are coming down, but there's still a few left to investigate, starting with the binomial failures, can I get you to run the following?  The quantile is returning zero in this case which is very strange:

```
#define BOOST_MATH_INSTRUMENT

#include <boost/math/distributions.hpp>
#include <iostream>

namespace boost::math::detail
{
   template <class RealType, class Policy>
   RealType quantile_imp_local(const binomial_distribution<RealType, Policy>& dist, const RealType& p, const RealType& q, bool comp)
   { // Quantile or Percent Point Binomial function.
     // Return the number of expected successes k,
     // for a given probability p.
     //
     // Error checks:
      BOOST_MATH_STD_USING  // ADL of std names
         RealType result = 0;
      RealType trials = dist.trials();
      RealType success_fraction = dist.success_fraction();
      if (false == binomial_detail::check_dist_and_prob(
         "boost::math::quantile(binomial_distribution<%1%> const&, %1%)",
         trials,
         success_fraction,
         p,
         &result, Policy()))
      {
         return result;
      }

      // Special cases:
      //
      if (p == 0)
      {  // There may actually be no answer to this question,
         // since the probability of zero successes may be non-zero,
         // but zero is the best we can do:
         BOOST_MATH_INSTRUMENT_VARIABLE(p);
         return 0;
      }
      if (p == 1 || success_fraction == 1)
      {  // Probability of n or fewer successes is always one,
         // so n is the most sensible answer here:
         BOOST_MATH_INSTRUMENT_VARIABLE(p);
         return trials;
      }
      if (p <= pow(1 - success_fraction, trials))
      { // p <= pdf(dist, 0) == cdf(dist, 0)
         BOOST_MATH_INSTRUMENT_VARIABLE(p);
         return 0; // So the only reasonable result is zero.
      } // And root finder would fail otherwise.

      // Solve for quantile numerically:
      //
      RealType guess = binomial_detail::inverse_binomial_cornish_fisher(trials, success_fraction, p, q, Policy());
      BOOST_MATH_INSTRUMENT_VARIABLE(guess);
      RealType factor = 8;
      if (trials > 100)
         factor = 1.01f; // guess is pretty accurate
      else if ((trials > 10) && (trials - 1 > guess) && (guess > 3))
         factor = 1.15f; // less accurate but OK.
      else if (trials < 10)
      {
         // pretty inaccurate guess in this area:
         if (guess > trials / 64)
         {
            guess = trials / 4;
            factor = 2;
         }
         else
            guess = trials / 1024;
      }
      else
         factor = 2; // trials largish, but in far tails.

      typedef typename Policy::discrete_quantile_type discrete_quantile_type;
      std::uintmax_t max_iter = policies::get_max_root_iterations<Policy>();
      result = detail::inverse_discrete_quantile(
         dist,
         comp ? q : p,
         comp,
         guess,
         factor,
         RealType(1),
         discrete_quantile_type(),
         max_iter);
      return result;
   } // quantile

}

int main()
{
   using namespace boost::math::policies;
   using namespace boost::math;
   
   typedef policy<discrete_quantile<integer_round_outwards> > Policy;
   binomial_distribution<double, Policy> dist(9079765771874083840, 0.561815);
   std::cout << boost::math::detail::quantile_imp_local(dist, 0.0365346, 1- 0.0365346, false) << std::endl;

   return 0;
}
```

**Comment by jzmaddock** [comment]
The other main errors are from autodiff, I can't tell from the output if these are small tolerance failures, or something more serious?

**Comment by jzmaddock** [comment]
Thanks @mborland : looks like the ibeta is going strangely wrong, OK can you try this one for me?  Thanks again!

```
#define BOOST_MATH_INSTRUMENT

#include <boost/math/distributions.hpp>
#include <boost/core/demangle.hpp>
#include <iostream>

namespace boost::math::detail
{
   template <class T, class Lanczos, class Policy>
   T ibeta_power_terms_inst(T a,
      T b,
      T x,
      T y,
      const Lanczos&,
      bool normalised,
      const Policy& pol,
      T prefix = 1,
      const char* function = "boost::math::ibeta<%1%>(%1%, %1%, %1%)")
   {
      BOOST_MATH_STD_USING

         if (!normalised)
         {
            // can we do better here?
            return pow(x, a) * pow(y, b);
         }

      T result;  // LCOV_EXCL_LINE

      T c = a + b;

      // combine power terms with Lanczos approximation:
      T agh = static_cast<T>(a + Lanczos::g() - 0.5f);
      T bgh = static_cast<T>(b + Lanczos::g() - 0.5f);
      T cgh = static_cast<T>(c + Lanczos::g() - 0.5f);
      BOOST_MATH_INSTRUMENT_VARIABLE(agh);
      BOOST_MATH_INSTRUMENT_VARIABLE(bgh);
      BOOST_MATH_INSTRUMENT_VARIABLE(cgh);
      if ((a < tools::min_value<T>()) || (b < tools::min_value<T>()))
         result = 0;  // denominator overflows in this case
      else
         result = Lanczos::lanczos_sum_expG_scaled(c) / (Lanczos::lanczos_sum_expG_scaled(a) * Lanczos::lanczos_sum_expG_scaled(b));
      result *= prefix;
      // combine with the leftover terms from the Lanczos approximation:
      result *= sqrt(bgh / boost::math::constants::e<T>());
      result *= sqrt(agh / cgh);
      BOOST_MATH_INSTRUMENT_VARIABLE(result);

      // l1 and l2 are the base of the exponents minus one:
      T l1 = (x * b - y * agh) / agh;
      T l2 = (y * a - x * bgh) / bgh;
      BOOST_MATH_INSTRUMENT_VARIABLE(l1);
      BOOST_MATH_INSTRUMENT_VARIABLE(l2);
      if (((std::min)(fabs(l1), fabs(l2)) < 0.2))
      {
         // when the base of the exponent is very near 1 we get really
         // gross errors unless extra care is taken:
         if ((l1 * l2 > 0) || ((std::min)(a, b) < 1))
         {
            //
            // This first branch handles the simple cases where either:
            //
            // * The two power terms both go in the same direction
            // (towards zero or towards infinity).  In this case if either
            // term overflows or underflows, then the product of the two must
            // do so also.
            // *Alternatively if one exponent is less than one, then we
            // can't productively use it to eliminate overflow or underflow
            // from the other term.  Problems with spurious overflow/underflow
            // can't be ruled out in this case, but it is *very* unlikely
            // since one of the power terms will evaluate to a number close to 1.
            //
            if (fabs(l1) < 0.1)
            {
               result *= exp(a * boost::math::log1p(l1, pol));
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
            else
            {
               result *= pow((x * cgh) / agh, a);
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
            if (fabs(l2) < 0.1)
            {
               result *= exp(b * boost::math::log1p(l2, pol));
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
            else
            {
               result *= pow((y * cgh) / bgh, b);
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
         }
         else if ((std::max)(fabs(l1), fabs(l2)) < 0.5)
         {
            //
            // Both exponents are near one and both the exponents are
            // greater than one and further these two
            // power terms tend in opposite directions (one towards zero,
            // the other towards infinity), so we have to combine the terms
            // to avoid any risk of overflow or underflow.
            //
            // We do this by moving one power term inside the other, we have:
            //
            //    (1 + l1)^a * (1 + l2)^b
            //  = ((1 + l1)*(1 + l2)^(b/a))^a
            //  = (1 + l1 + l3 + l1*l3)^a   ;  l3 = (1 + l2)^(b/a) - 1
            //                                    = exp((b/a) * log(1 + l2)) - 1
            //
            // The tricky bit is deciding which term to move inside :-)
            // By preference we move the larger term inside, so that the
            // size of the largest exponent is reduced.  However, that can
            // only be done as long as l3 (see above) is also small.
            //
            bool small_a = a < b;
            T ratio = b / a;
            if ((small_a && (ratio * l2 < 0.1)) || (!small_a && (l1 / ratio > 0.1)))
            {
               T l3 = boost::math::expm1(ratio * boost::math::log1p(l2, pol), pol);
               BOOST_MATH_INSTRUMENT_VARIABLE(l3);
               l3 = l1 + l3 + l3 * l1;
               BOOST_MATH_INSTRUMENT_VARIABLE(l3);
               l3 = a * boost::math::log1p(l3, pol);
               BOOST_MATH_INSTRUMENT_VARIABLE(l3);
               result *= exp(l3);
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
            else
            {
               T l3 = boost::math::expm1(boost::math::log1p(l1, pol) / ratio, pol);
               l3 = l2 + l3 + l3 * l2;
               l3 = b * boost::math::log1p(l3, pol);
               result *= exp(l3);
               BOOST_MATH_INSTRUMENT_VARIABLE(result);
            }
         }
         else if (fabs(l1) < fabs(l2))
         {
            // First base near 1 only:
            T l = a * boost::math::log1p(l1, pol)
               + b * log((y * cgh) / bgh);
            if ((l <= tools::log_min_value<T>()) || (l >= tools::log_max_value<T>()))
            {
               l += log(result);
               if (l >= tools::log_max_value<T>())
                  return policies::raise_overflow_error<T>(function, nullptr, pol);  // LCOV_EXCL_LINE we can probably never get here, probably!
               result = exp(l);
            }
            else
               result *= exp(l);
            BOOST_MATH_INSTRUMENT_VARIABLE(result);
         }
         else
         {
            // Second base near 1 only:
            T l = b * boost::math::log1p(l2, pol)
               + a * log((x * cgh) / agh);
            if ((l <= tools::log_min_value<T>()) || (l >= tools::log_max_value<T>()))
            {
               l += log(result);
               if (l >= tools::log_max_value<T>())
                  return policies::raise_overflow_error<T>(function, nullptr, pol);  // LCOV_EXCL_LINE we can probably never get here, probably!
               result = exp(l);
            }
            else
               result *= exp(l);
            BOOST_MATH_INSTRUMENT_VARIABLE(result);
         }
      }
      else
      {
         // general case:
         T b1 = (x * cgh) / agh;
         T b2 = (y * cgh) / bgh;
         l1 = a * log(b1);
         l2 = b * log(b2);
         BOOST_MATH_INSTRUMENT_VARIABLE(b1);
         BOOST_MATH_INSTRUMENT_VARIABLE(b2);
         BOOST_MATH_INSTRUMENT_VARIABLE(l1);
         BOOST_MATH_INSTRUMENT_VARIABLE(l2);
         if ((l1 >= tools::log_max_value<T>())
            || (l1 <= tools::log_min_value<T>())
            || (l2 >= tools::log_max_value<T>())
            || (l2 <= tools::log_min_value<T>())
            )
         {
            // Oops, under/overflow, sidestep if we can:
            if (a < b)
            {
               T p1 = pow(b2, b / a);
               T l3 = (b1 != 0) && (p1 != 0) ? (a * (log(b1) + log(p1))) : tools::max_value<T>(); // arbitrary large value if the logs would fail!
               if ((l3 < tools::log_max_value<T>())
                  && (l3 > tools::log_min_value<T>()))
               {
                  result *= pow(p1 * b1, a);
               }
               else
               {
                  l2 += l1 + log(result);
                  if (l2 >= tools::log_max_value<T>())
                     return policies::raise_overflow_error<T>(function, nullptr, pol);  // LCOV_EXCL_LINE we can probably never get here, probably!
                  result = exp(l2);
               }
            }
            else
            {
               // This protects against spurious overflow in a/b:
               T p1 = (b1 < 1) && (b < 1) && (tools::max_value<T>() * b < a) ? static_cast<T>(0) : static_cast<T>(pow(b1, a / b));
               T l3 = (p1 != 0) && (b2 != 0) ? (log(p1) + log(b2)) * b : tools::max_value<T>();  // arbitrary large value if the logs would fail!
               if ((l3 < tools::log_max_value<T>())
                  && (l3 > tools::log_min_value<T>()))
               {
                  result *= pow(p1 * b2, b);
               }
               else if (result != 0)  // we can elude the calculation below if we're already going to be zero
               {
                  l2 += l1 + log(result);
                  if (l2 >= tools::log_max_value<T>())
                     return policies::raise_overflow_error<T>(function, nullptr, pol);  // LCOV_EXCL_LINE we can probably never get here, probably!
                  result = exp(l2);
               }
            }
            BOOST_MATH_INSTRUMENT_VARIABLE(result);
         }
         else
         {
            // finally the normal case:
            result *= pow(b1, a) * pow(b2, b);
            BOOST_MATH_INSTRUMENT_VARIABLE(result);
         }
      }

      BOOST_MATH_INSTRUMENT_VARIABLE(result);

      if (0 == result)
      {
         if ((a > 1) && (x == 0))
            return result;  // true zero LCOV_EXCL_LINE we can probably never get here
         if ((b > 1) && (y == 0))
            return result; // true zero LCOV_EXCL_LINE we can probably never get here
         return boost::math::policies::raise_underflow_error<T>(function, nullptr, pol);
      }

      return result;
   }

}

int main()
{
   using namespace boost::math::policies;
   using namespace boost::math;
   
   typedef policy<discrete_quantile<integer_round_outwards> > Policy;
   typedef typename lanczos::lanczos<double, Policy>::type lanczos_type;

   std::cout << boost::core::demangle(typeid(lanczos_type).name()) << std::endl;

   std::cout << boost::math::detail::ibeta_power_terms_inst(3.9786171674284134e+18, 5.1011486044456704e+18, 0.43818500000000005, 0.56181499999999995, lanczos_type(), true, Policy()) << std::endl;

   return 0;
}
```

Output should be:

```
struct boost::math::lanczos::lanczos13m53
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:41 agh = 3978617167428413440
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:42 bgh = 5101148604445670400
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:43 cgh = 9079765771874083840
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:52 result = 149592859187.68817138671875
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:57 l1 = -6.7354244935610946714562483311327518e-10
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:58 l2 = 5.2532630585679715818840706802075706e-10
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:125 l3 = 6.7354244940602464723437159686879674e-10
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:127 l3 = -4.0374425102950054010357025410984728e-19
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:129 l3 = -1.6063438083964978186912730961921625
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:131 result = 30011286371.699993133544921875
D:\data\boost\boost\IDE\vs2022\math\scrap\scrap.cpp:238 result = 30011286371.699993133544921875
30011286371.699993133544921875
```

**Comment by mborland** [comment]
@jzmaddock Here it is:

Clang-18

```
boost::math::lanczos::lanczos13m53
scrap.cpp:36 agh = 3978617167428413440
scrap.cpp:37 bgh = 5101148604445670400
scrap.cpp:38 cgh = 9079765771874083840
scrap.cpp:47 result = 149592859187.688201904296875
scrap.cpp:52 l1 = -6.735424769136304369763995610412028e-10
scrap.cpp:53 l2 = 5.2532629155828719625358083980537494e-10
scrap.cpp:120 l3 = 6.7354243107331720116055823554634778e-10
scrap.cpp:122 l3 = -4.6293972673147390445287398339587954e-17
scrap.cpp:124 l3 = -184.18599442584604730654973536729813
scrap.cpp:126 result = 1.5273896380250717763985214018598168e-69
scrap.cpp:233 result = 1.5273896380250717763985214018598168e-69
1.5273896380250717763985214018598168e-69
```

GCC-13
```
boost::math::lanczos::lanczos13m53
scrap.cpp:36 agh = 3978617167428413440
scrap.cpp:37 bgh = 5101148604445670400
scrap.cpp:38 cgh = 9079765771874083840
scrap.cpp:47 result = 149592859187.688201904296875
scrap.cpp:52 l1 = -6.7354244935610946714562483311327518e-10
scrap.cpp:53 l2 = 5.2532630585679715818840706802075706e-10
scrap.cpp:120 l3 = 6.7354244940602464723437159686879674e-10
scrap.cpp:122 l3 = -4.0374425102950054010357025410984728e-19
scrap.cpp:124 l3 = -1.6063438083964978186912730961921625
scrap.cpp:126 result = 30011286371.700000762939453125
scrap.cpp:233 result = 30011286371.700000762939453125
30011286371.700000762939453125
```

**Comment by jzmaddock** [comment]
Thanks Matt, this might be a tough one: the incomplete beta is basically returning garbage (all digits in the log terms cancel out).  Will have to think about this...

**Comment by jzmaddock** [comment]
@NAThompson : cubic_roots_test is generating NaN's, but only in Clang C++20 mode: any ideas?

**Comment by jzmaddock** [comment]
Apart from a network failure in drone, this is passing now... merging.

**Pull request merged**
