### PR TITLE
Add MSVC-2022 to CI Testing

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by NAThompson** [comment]
Does the one support modules?

**Comment by jzmaddock** [comment]
> Does the one support modules?

Yes, as does the existing VS2019.

**Comment by mborland** [comment]
@jzmaddock As the MSVC guru does the failure in `test_next` make sense to you? Some kind of change to default rounding mode in the new release?

**Comment by jzmaddock** [comment]
No, but I see it's officially released now so I'm downloading as I speak...

BTW, C++11 testing is redundant for msvc - it only supports C++14/17/20.

**Comment by jzmaddock** [comment]
I'm pretty much stumped on this, I'm unable to reproduce locally at all (which is to say all tests pass with msvc-14.3, compiler version matches that in the test suite).  Can anyone else have a try?

**Comment by mborland** [comment]
I installed a copy of Visual Studio 2022, and am also unable to reproduce this error locally.

**Comment by jzmaddock** [comment]
Now that VS2022 is released, lets kick this off again....

**Comment by jzmaddock** [comment]
Matt the failures here I've just been hit with in multiprecision as well: the meaning of "windows-latest" has just changed, we need to change that to "windows-2019", otherwise everything breaks! :(

**Comment by jzmaddock** [comment]
Never mind, apparently I can commit direct to this branch via the web-interface, CI updated and we'll see what happens.

**Comment by NAThompson** [comment]
> Never mind, apparently I can commit direct to this branch via the web-interface, CI updated and we'll see what happens.

@jzmaddock : Try `gh pr checkout 720` using [this](https://cli.github.com/manual/gh); I believe that Matt always clicks the "allow edits from maintainers" button so it's easy to collaborate.

**Comment by mbs-c** [comment]
I investigated a bit further and the root cause seems to be that `ldexp(long double, int)`, which is called from `float_prior_imp`, returns different values. When called from `test_next`, `std::ldexp(1.0L, -1075)` returns `4.94066e-324` inside the Windows container and `0` outside.

In both cases, the `real_concept` test case prints "Denormals are flushed to zero." in the beginning.

**Pull request merged**
