### PR TITLE
Fix for CMake superproject failure

### PR DESCRIPTION
**Pull request by mborland**
See issue #614.

### CODE REVIEW

**Comment by mborland** [comment]
@jzmaddock Pending review I think this is good. I see that drone is running now on this PR so thank you for that.

**Comment by jzmaddock** [comment]
My only question is have you run the super-project CMake project to check there are no longer conflicts?

**Comment by mborland** [comment]
I did; locally the super-project build succeeds now.

**Comment by jzmaddock** [comment]
Thanks Matt!

**Pull request merged**
