### PR TITLE
Fix for issue #585

### PR DESCRIPTION
**Pull request by mborland**
Provides thread synchronization if using the MSVC implementation of the Parallel TS.

### CODE REVIEW

**Comment by NAThompson** [comment]
What's the performance implications of this diff? Could you run the benchmarks?

**Comment by mborland** [comment]
I expect that the performance penalty will be high maybe to the point where it is better off just running the sequential method. I have been meaning to create a MSVC environment; should have benchmarks up in the next day or two.

**Comment by jzmaddock** [comment]
After a minor correction to the lambda, this still fails I'm afraid :(

**Comment by mborland** [comment]
> After a minor correction to the lambda, this still fails I'm afraid :(

OK. I will get MSVC up and running on my end to troubleshoot and re-benchmark.

**Comment by mborland** [comment]
The new implementation takes the decomposition method from the first four moments calculation. This maintains the required sorting. Clean on tsan with both Clang 12 and GCC 11. New benchmarks:

```
gini_coefficient<double>/real_time_BigO                   1.09 N          1.08 N    
gini_coefficient<double>/real_time_RMS                      13 %            13 %
parallel_gini_coefficient<double>/real_time_BigO          0.88 N          0.82 N    
parallel_gini_coefficient<double>/real_time_RMS             36 %            39 %
```

**Comment by mborland** [comment]
Any changes for this one? The only CI failure is from CircleCI from before the config was committed.

**Comment by jzmaddock** [comment]
Looks good to me, @NAThompson ?

**Comment by NAThompson** [comment]
I think this is now *correct*, but I'm not sure the parallelism is worth it; it seems the speedup  is not so impressive.

What about using the parallel sort from the standard library? If you use that first, then you can reason much more clearly about a parallel computation of the Gini coefficient.

(Note: This is just a suggestion. I believe this PR can be merged if @mborland desires; we don't need to make every PR a research program.)

**Comment by mborland** [comment]
> I think this is now _correct_, but I'm not sure the parallelism is worth it; it seems the speedup is not so impressive.
> 
> What about using the parallel sort from the standard library? If you use that first, then you can reason much more clearly about a parallel computation of the Gini coefficient.

Passing an execution policy to `std::is_sorted` and `std::sort` is [used here.](https://github.com/boostorg/math/blob/1924e3179c24ac4d73181587d752774ad72c0ccb/include/boost/math/statistics/univariate_statistics.hpp#L416-L424) I agree the speedup is not impressive. Another interface could be added where a distribution function is taken as input to directly calculate the gini coefficient (much like is done to compare against a uniform distribution in the test cases). I do not know if implementing all of those would be value added.

**Pull request merged**
