### PR TITLE
Fixed extra semicolon warnings

### PR DESCRIPTION
**Pull request by Kojoley**
```
boost/math/constants/constants.hpp:268:200: warning: extra ';' [-Wpedantic]
   BOOST_DEFINE_MATH_CONSTANT(sixth, 1.666666666666666666666666666666666666e-01, "1.66666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667e-01");
                                                                                                                                                                                                        ^
boost/math/constants/constants.hpp:304:208: warning: extra ';' [-Wpedantic]
   BOOST_DEFINE_MATH_CONSTANT(exp_minus_one, 3.678794411714423215955237701614608674e-01, "3.67879441171442321595523770161460867445811131031767834507836801697461495744899803357147274345919643746627325277e-01");
                                                                                                                                                                                                                ^
```

### CODE REVIEW

**Comment by NAThompson** [comment]
What compiler did you find this on?

**Comment by Kojoley** [comment]
GCC

**Comment by NAThompson** [comment]
Flags?

**Comment by Kojoley** [comment]
`-pedantic`

**Comment by NAThompson** [comment]
Ok, it is indeed pretty terrifying to see that pile of warnings.

**Comment by jzmaddock** [comment]
Thanks for that - those fixes are already in develop so closing down.

**Pull request closed without merging**
