### PR TITLE
Gcd unit tests

### PR DESCRIPTION
**Pull request by jeremy-murphy**
A few basic gcd unit tests.

### CODE REVIEW

**Comment by jeremy-murphy** [comment]
Any thoughts on this PR? I think it is fine as is although minimal; I could add some more variety to the values tested just to increase confidence in correctness.

**Comment by pabristow** [comment]
You have never have too many tests ;-)

 

(and examples of use).

 

Paul

**Comment by jeremy-murphy** [comment]
Well, I think that's mostly true because most of the time people don't write enough tests.

But in the case of algorithms as simple as Euclidean gcd, I struggle to think of new examples that actually test something novel. Admittedly, 'binary' gcd is more complex, but there just aren't many code paths through Euclidean gcd, right? (And I intend to make it even simpler.)

I really value good tests, but I don't want to add more just for the sake of it (slightly contrary to what I said above). I'll keep thinking about it for a few days and I welcome suggestions.

**Comment by jzmaddock** [comment]
Looks good to me, have you checked code coverage?

**Pull request merged**
