### PR TITLE
Tanh-sinh with MPFR test.

### PR DESCRIPTION
**Pull request by NAThompson**

### CODE REVIEW

**Comment by jzmaddock** [comment]
There's something strange going on in the original test case - I don't see why the checks in itrunc are failing?  So this might be an issue with mpfr_float....

**Comment by NAThompson** [comment]
@jzmaddock : I noticed that as well, but concluded it was a separate issue. In any case, I realized that `itrunc` really needed to be a `lltrunc` in order to match the size of the lhs . . .

**Comment by jzmaddock** [comment]
Nah, my bad.  It's overflow in `sqrt((2 - x) / x` that's the issue.

**Comment by NAThompson** [comment]
The build failures come from the known issue in serialization.

**Pull request merged**
