### PR TITLE
Improve test coverage.

### PR DESCRIPTION
**Pull request by jzmaddock**
Try and get all the special_functions/a*.hpp files up to 100%.

### CODE REVIEW

**Comment by jzmaddock** [comment]
Refs https://github.com/boostorg/math/issues/1068

**Comment by ckormanyos** [comment]
Dude it's massive +3 persent in one swath!

**Comment by jzmaddock** [comment]
OK folks, I hope this tranche of coverage improvement is good to go, I'll start a fresh PR for any more before the changes here get out of hand.  @NAThompson there are a couple of drone failures in random_search_test which appear unrelated - tolerance too tight, or something non-deterministic in there?

**Comment by ckormanyos** [comment]
> merging over the failure and I'll hopefully figure this one out pretty quick . . .

done. merged. Thank you John.

**Comment by ckormanyos** [comment]
I guess I need to revert that commit? I hope I did not turn this into a mess.

**Comment by jzmaddock** [comment]
> Ughhhh wait a minute. I just merged your branch. Not mine.

Should be OK ;)

> I recommend merging over the failure and I'll hopefully figure this one out pretty quick . . .

OK lets see what happens on develop

**Comment by jzmaddock** [comment]
> I guess I need to revert that commit? I hope I did not turn this into a mess.

Should be OK unless someone notices any SNAFU's.

**Comment by ckormanyos** [comment]
Indeed. I would just end up fumbling the fumble. I will merge my dos to develop.

Then we just have the remaining very few test failures.

**Comment by ckormanyos** [comment]
> Should be OK unless someone notices any SNAFU's.

Thanky you John! Probably, with your expert help (as usual) we can dig out of this.

OK, so finally, I merged the new docs. This contains all your new coverage stuff. The docs look good, but the very few test failures are still present.

**Comment by ckormanyos** [comment]
>> Should be OK 

> Thanky you John!

As far as I can tell, everything is now OK on develop. @NAThompson triggered a few runs in his new work in #1083, and drone, GHA are OK there. Thanks again @jzmaddock, and sorry about the back-and-forth.

**Pull request merged**
