### PR TITLE
Remove MPL from constants

### PR DESCRIPTION
**Pull request by mborland**
Remove MPL, and other C++11 changes.

### CODE REVIEW

**Comment by jzmaddock** [comment]
We probably should remove use of boost::integral_constant, but it will need a coordinated change inside Multiprecision.

**Comment by mborland** [comment]
I will open a PR in multiprecision to make the change, and put `std::integral_constant` back in here.

**Comment by mborland** [comment]
Both this and https://github.com/boostorg/multiprecision/pull/294 replace `boost::integral_constant` with `std::integral_constant` now.

**Comment by jzmaddock** [comment]
Merged, both this and Multiprecision will be shown as failing until the boost super-project updates.

**Pull request merged**
