### PR TITLE
Algorithm 4.5.2C: gcd of n integers

### PR DESCRIPTION
**Pull request by jeremy-murphy**
A fairly trivial algorithm but necessary for calculating the gcd of polynomials over a unique factorization domain.

### CODE REVIEW

**Comment by jeremy-murphy** [comment]
What do you think of the name, `gcd_n`? I thought about calling it just `gcd` but it seemed like a lot of template magic to distinguish it from the other 2-arity `gcd` functions, and after all I guess it is a different algorithm.

**Comment by jzmaddock** [comment]
Name is a good question, in C++11 land we could make gcd a variadic template that accepts n arguments, and I can see genuine uses for this, but your range-based version has good uses to.

Maybe ask on the mailing list for suggestions?

**Comment by jeremy-murphy** [comment]
This is ready to go from my end, I'm happy with `gcd_range`.

**Comment by jeremy-murphy** [comment]
OK, I've changed it to return the iterator position at termination too.

**Pull request merged**
