### PR TITLE
update for boost ticket #1827

### PR DESCRIPTION
**Pull request by akumta**

### CODE REVIEW

**Comment by jzmaddock** [comment]
Confirmed that fixes things.  Can we please delete the redundant using statements rather than comment them out?

**Comment by akumta** [comment]
Yes ofcourse. How do  update this via the browser?

**Comment by jzmaddock** [comment]
On 02/12/2015 18:31, akumta wrote:
> Yes ofcourse. How do update this via the browser?

Select the "files changed" tab and then use the edit button - I'd do it 
myself, but I don't have permissions to edit your PR.

Best, John.

**Comment by akumta** [comment]
Done.

Thanks,

Aparna

**Comment by jzmaddock** [comment]
Thanks!

**Pull request merged**
