### PR TITLE
Relativize the error in the Lambert-W tests to the condition number o…

### LINKED ISSUE #328: Lambert-W test tolerances are too stringent or test values lack precision.
Compiled with `g++-9`, we have:

```
$ ./test_lambert_w.x
Running 2 test cases...
GCC 9.2.0

Testing type f
Tolerance 2 * epsilon == 2.38419e-07
Precision 6 decimal digits, max_digits10 = 9
-exp(-1) = -0.367879450

Testing type d
Tolerance 2 * epsilon == 4.44089e-16
Precision 15 decimal digits, max_digits10 = 17
-exp(-1) = -0.36787944117144233

Testing type e
Tolerance 16 * epsilon == 1.73472e-18
Precision 18 decimal digits, max_digits10 = 21
-exp(-1) = -0.367879441171442321583

Testing type N5boost4math8concepts12real_conceptE
Tolerance 2 * epsilon == 2.1684e-19
Precision 0 decimal digits, max_digits10 = 0
-exp(-1) = -0.4

BOOST_MATH_TEST_FLOAT128 NOT defined so NO float128 tests.
Tolerance 1 * epsilon == 2.22045e-16
test_lambert_w.cpp:1035: error: in "test_range_of_double_values": difference{2.61848e-09} between lambert_w0(create_test_value<RealType>( -0.36787944117144228Q, "-0.36787944117144228", boost::integral_constant<bool, std::numeric_limits<RealType>::is_specialized && (std::numeric_limits<RealType>::radix == 2) && (std::numeric_limits<RealType>::digits <= 113) && boost::is_convertible<largest_float, RealType>::value>(), boost::integral_constant<bool, boost::is_constructible<RealType, const char*>::value>())){-0.99999998154505632} and create_test_value<RealType>( -0.99999997892657588Q, "-0.99999997892657588", boost::integral_constant<bool, std::numeric_limits<RealType>::is_specialized && (std::numeric_limits<RealType>::radix == 2) && (std::numeric_limits<RealType>::digits <= 113) && boost::is_convertible<largest_float, RealType>::value>(), boost::integral_constant<bool, boost::is_constructible<RealType, const char*>::value>()){-0.99999997892657588} exceeds 2.2204460492503131e-16
test_lambert_w.cpp:1040: error: in "test_range_of_double_values": difference{4.64453e-10} between lambert_w0(create_test_value<RealType>( -0.36787944117144222Q, "-0.36787944117144222", boost::integral_constant<bool, std::numeric_limits<RealType>::is_specialized && (std::numeric_limits<RealType>::radix == 2) && (std::numeric_limits<RealType>::digits <= 113) && boost::is_convertible<largest_float, RealType>::value>(), boost::integral_constant<bool, boost::is_constructible<RealType, const char*>::value>())){-0.9999999746548851} and create_test_value<RealType>( -0.99999997419043196Q, "-0.99999997419043196", boost::integral_constant<bool, std::numeric_limits<RealType>::is_specialized && (std::numeric_limits<RealType>::radix == 2) && (std::numeric_limits<RealType>::digits <= 113) && boost::is_convertible<largest_float, RealType>::value>(), boost::integral_constant<bool, boost::is_constructible<RealType, const char*>::value>()){-0.99999997419043196} exceeds 2.2204460492503131e-16
(std::numeric_limits<RealType>::min)() 2.2250738585072014e-308

*** 2 failures are detected in the test module "Master Test Suite"
```

The issue is that the condition number of function evaluation near these test points is tending to infinity, so any change in rounding in any part of the computation is causing large changes in the result.

### PR DESCRIPTION
**Pull request by NAThompson**
…f function evaluation.

Fixes #328

### CODE REVIEW

**Comment by pabristow** [comment]
looks sensible (assuming it passes :-) )

It would be useful to document these error bounds in our documentation.  Long ago I tried to do this but failed to get the Corless original info and left it unfinished.  If you can get access to a copy and share it that would be useful.  The Dawson reference is also useful if I haven't referenced already.

**Comment by NAThompson** [comment]
@pabristow : You mean [this one](https://www.uwo.ca/apmaths/faculty/jeffrey/pdfs/W-adv-cm.pdf)?

**Comment by NAThompson** [comment]
> It would be useful to document these error bounds in our documentation. 

The error bound I used there is a property of every differentiable function. Strangely it is not very well known, so it still might be reasonable to document it. In any case there is a [wikipedia entry](https://en.wikipedia.org/wiki/Condition_number#One_variable)!

**Comment by NAThompson** [comment]
@jzmaddock : It seems I don't have permissions to rerun the failed jobs. Could you either give me permissions (I just got an AppVeyor account) or kick off a rerun?

**Comment by jzmaddock** [comment]
Done both.

**Pull request merged**
