### PR TITLE
Add GCC11 to CI

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by NAThompson** [comment]
While we're adding compilers to test, are there any which can be sensibly removed? We've got a really computationally expensive build  . . .

**Comment by mborland** [comment]
> While we're adding compilers to test, are there any which can be sensibly removed? We've got a really computationally expensive build . . .

It looks like drone tests g++-6,8,10 and clang-10. We could run g++-5,7,9,11 and clang-5,6,7,8,9,11 using GHA. That would cut down a good bit. We could make further cuts and go odd versions numbers on GHA, and even numbers on drone. I do not know what the limitations for run time etc. are imposed by drone (if any).

Thoughts @NAThompson and @jzmaddock?

**Comment by NAThompson** [comment]
I'd probably get rid of gcc-5 and clang-5.

**Comment by NAThompson** [comment]
Build failure was a timeout.

**Pull request merged**
