### PR TITLE
Thread guards in stats

### PR DESCRIPTION
**Pull request by mborland**
Allows for use of stats functions in single threaded environments. See issue #621

### CODE REVIEW

**Comment by mborland** [comment]
@jzmaddock I am not quite sure I understand the rash of clang 9 failures on this one. All of the C++20 failures look to be stemming from the standard library, and the quadrature failures are all memory access violations. All the drone tests pass (including ASAN) [except one](https://drone.cpp.al/boostorg/math/209/132/1) which is a failure on Drone's end.

**Comment by jzmaddock** [comment]
It seems to be *all* the Monte Carlo tests that are failing, @NAThompson any ideas?

**Comment by NAThompson** [comment]
Wow! I have *no* clue. It looks like this change doesn't have anything to do with the Monte-Carlo integration. . .

We did have an ASAN build that should've caught this before if it was in user-space, right?

Question: Is there utility in having a single-threaded Monte-Carlo integrator? I personally feel the design of that class is *fundamentally* multithreaded.

**Comment by jzmaddock** [comment]
I have a dim memory that I disabled sanitizers for the Monte Carlo tests because they take way too long to run (and/or run the machine out of memory).  Might be worth running them locally to see if that gives any clue....  currently struggling with my own (unrelated) thread safety bug yours...

**Comment by mborland** [comment]
> I have a dim memory that I disabled sanitizers for the Monte Carlo tests because they take way too long to run (and/or run the machine out of memory). Might be worth running them locally to see if that gives any clue.... currently struggling with my own (unrelated) thread safety bug yours...

Locally using Clang-12's ASAN yields clean results on the Monte Carlo tests.

**Comment by NAThompson** [comment]
Ok, my vote is to *not* disable threads for Monte-Carlo integration. There's little sense in it-the design is fundamentally multithreaded.

**Comment by mborland** [comment]
> Ok, my vote is to *not* disable threads for Monte-Carlo integration. There's little sense in it-the design is fundamentally multithreaded.

I can revert the change and have it throw an error in single threaded environments.

**Comment by mborland** [comment]
> > Ok, my vote is to _not_ disable threads for Monte-Carlo integration. There's little sense in it-the design is fundamentally multithreaded.
> 
> I can revert the change and have it throw an error in single threaded environments.

So after review the thread guards were not added to Monte-Carlo integration in #628. Last time it was touched was over 6 weeks ago by #600. I am still stumped as to why clang-9 is so unhappy.

**Comment by NAThompson** [comment]
I repeat my unpopular opinion: CI is here to serve us, we don't live to serve CI. If we've run it locally under thread sanitizer, and it's clean, it seems like this is unlikely any users will be bitten by it.

**Comment by jzmaddock** [comment]
I have some inscrutable thread-based failures with clang-9 in Multiprecision also, so I've pushed this: https://github.com/boostorg/math/pull/631 to sanity check the std lib thread support.

**Comment by jzmaddock** [comment]
CI has now been adjusted on develop, @mborland is this now good to go?

**Comment by jzmaddock** [comment]
Nod.  If you don't mind merging develop into this just be on the safe side, that would great!

**Pull request merged**
