### PR TITLE
Improve NAN handling in ccmath

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Review by pulver — COMMENTED** [review]
For the `hypot()`, `log()`, and `sqrt()` functions, shouldn't parameters with values of negative infinity result in NaN instead of negative infinity?

E.g. `sqrt(-∞) = nan` rather than `-∞`.

I know this behavior remains unchanged in this PR, but thought this might be an opportune time to fix.

**Comment by mborland** [comment]
> For the `hypot()`, `log()`, and `sqrt()` functions, shouldn't parameters with values of negative infinity result in NaN instead of negative infinity?
> 
> E.g. `sqrt(-∞) = nan` rather than `-∞`.
> 
> I know this behavior remains unchanged in this PR, but thought this might be an opportune time to fix.

The language specification is [+- infinity returns +- infinity](https://en.cppreference.com/w/cpp/numeric/math/hypot). Since we fallback to the STL at runtime I didn't want the edge case handling to differ based on context.

**Comment by jzmaddock** [comment]
> The language specification is [+- infinity returns +- infinity](https://en.cppreference.com/w/cpp/numeric/math/hypot). Since we fallback to the STL at runtime I didn't want the edge case handling to differ based on context.

C99 at least specifies that sqrt of a negative number is a domain error and yields a NaN, as things stand runtime sqrt(-INF) returns NaN and constexpr sqrt(-INF) returns +INF which looks just plain wrong?

**Comment by mborland** [comment]
> > The language specification is [+- infinity returns +- infinity](https://en.cppreference.com/w/cpp/numeric/math/hypot). Since we fallback to the STL at runtime I didn't want the edge case handling to differ based on context.
> 
> C99 at least specifies that sqrt of a negative number is a domain error and yields a NaN, as things stand runtime sqrt(-INF) returns NaN and constexpr sqrt(-INF) returns +INF which looks just plain wrong?

Ok for `sqrt` the standard only specifies +inf. Domain error is implementation defined so NaN would make sense.

**Comment by pulver** [comment]
According to https://en.cppreference.com/w/c/numeric/math/logb

> If arg is ±∞, +∞ is returned

I haven't tested it, but inspecting the code it appears that for the `constexpr` version
```
logb(-∞) = -∞
```
Shouldn't it return `+∞`?

**Comment by mborland** [comment]
> According to https://en.cppreference.com/w/c/numeric/math/logb
> 
> > If arg is ±∞, +∞ is returned
> 
> I haven't tested it, but inspecting the code it appears that for the `constexpr` version
> 
> ```
> logb(-∞) = -∞
> ```
> 
> Shouldn't it return `+∞`?

Yes; the change is wrong.

**Comment by mborland** [comment]
@pulver Can you do one last dummy check for me? I think this is good now and addresses your `sqrt(-∞) = nan`.

**Review by pulver — COMMENTED** [review]
For `hypot()`, it looks like
```
hypot(-∞,1) = -∞
```
but should return +∞. Same when x and y are swapped, based on [hypot](https://en.cppreference.com/w/cpp/numeric/math/hypot):
 
> if one of the arguments is ±∞, hypot(x,y) returns +∞ even if the other argument is NaN

**Review by pulver — APPROVED** [review]
LGTM

**Pull request merged**
