### PR TITLE
Remove missing test from Jamfile.

### PR DESCRIPTION
**Pull request by jeremy7nelson**

### CODE REVIEW

**Comment by jzmaddock** [comment]
@NAThompson are you able to add the missing file ASAP?  If not I'll merge this later as it blocks the regression testers from running.

**Comment by jeremy7nelson** [comment]
The file was renamed. So the old file should be removed.

Sent from my iPhone

On Sep 7, 2019, at 1:13 AM, jzmaddock <notifications@github.com> wrote:

@NAThompson <https://github.com/NAThompson> are you able to add the missing
file ASAP? If not I'll merge this later as it blocks the regression testers
from running.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/boostorg/math/pull/250?email_source=notifications&email_token=AEAM2VZWGDBJJDNC6MUEMW3QINPBXA5CNFSM4IUN7UA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6ETH3Y#issuecomment-529085423>,
or mute the thread

**Comment by NAThompson** [comment]
@jzmaddock : My bad; merging.

@jeremy7nelson : Thanks for the fix!

**Comment by jzmaddock** [comment]
Actually the test should have been renamed in the Jamfile rather than removed - just pushed.

**Comment by NAThompson** [comment]
@jzmaddock : Disappointing lack of discipline here on my part.

@jeremy7nelson : Just curious, are you consuming develop in your own projects, or using release branches?

**Comment by jeremy7nelson** [comment]
I used to use boost releases in my C++ code, but since the functionality I need is now part of std I don't need it anymore. Running the regression tests as a side project is one way I can give back. I only run tests on develop because my master results don't show on the website. Does anyone know how to get results for master reported?

**Comment by jeremy7nelson** [comment]
It was a little confusing. The test was renamed but the old test was not removed from the Jamfile (although it was removed from the example Jamfile, LOL).

**Comment by NAThompson** [comment]
Well, it looks like we need the extra pair of eyes; thanks!

**Pull request merged**
